name: The Tito Blog
description: "Tips, tricks, news and features related to organising events"
url: http://blog.tito.io
pygments: true
# defaults
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
